---
title: "Checklist of common JMLR formatting errors"
author: "Nick Spyrison"
date: "8/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Following: https://www.jmlr.org/format/formatting-errors.html

Transactions JMLR - TMLR submissions: https://openreview.net/group?id=TMLR, submission


# Checklist of common JMLR formatting errors

## General

- One LaTeX file: The latex for the paper should be in one file. Otherwise it takes too much additional time for the production staff to perform all of the checks before publication. NS
- Make sure your abstract reads well. It will be used to advertise your paper. 
- We recommend you use small caps for system names. (In LaTex that's \\sc). NA?
- Move file to have correct name, according to the JMLR naming conventions. See the authors' guide. _NEEDED_
- Signed copyright form: Do not forget to provide this. _NEEDED_
- Text should be in Computer Modern. _Don't see where to set_
- Order of paper: At the end of your paper, the order of sections should be: Acknowledgments, Appendices, then References. _Not the order of the template, may need an eye on this._
- Acknowledgments should be a unnumbered section. You can use the \\acks{} command for this. NS
- Appendix section number should be a letter (Should look like Appendix A. Title). You can use \\appendix followed by regular \\section command to format appendices. NS

## Title Area

- Capitalization of paper title: In the title area, the paper title should be in title case. (First letter of each word capitalized except for little words like "and" and "or".). NS
- Author contact addresses: These should be complete enough that mail sent to that address will reach them. NS
- Editor listed: Please include the name of the Action Editor who handled your submission in the \\editor{} tag _todo after inital submission_
- Keyword: Please add keywords to your article using \\begin{keywords} ... \\end{keywords} after your abstract. They should not be capitalised, they should be separated by commas, and they should not have a period at the end. NS
- Abstract: Do not delete the % at the end of \\begin{abstract}% as it introduces an extra indent. _NS---doesn't get added in .rmd, may need to watch submission_
- Title should be split across two lines, only when it is too long for one line. NS

## Headers and Footers
- Front page header: Use the \\jmlrheading command to get a correct header and footer on the title page. NA
- Copyright notice, bottom of front page uses authors full names: In the \\jmlrheading command, please use the full names of all authors. NS
- Running headers: Add running headers to your paper using the \\ShortHeadings command. Please see the example paper on the web site for how to do this. NS
- Running headers: In the \\ShortHeadings command, please capitalise the words in your paper title. NS
- Running headers: In the author list in the \\ShortHeadings command, please use "and" before the last author. NS
- Running headers: The ShortHeadings author list should have last names only, and should list all authors if possible. If you have many authors, "et al" is acceptable. NS

## Section Headers

- No unnumbered sections: We do not use \\paragraph or \\section*. We do not allow bold, unindented text to begin a paragraph that could be mistaken for a section header. If it looks like a section header it needs to be numbered like a section header, otherwise it needs to be formatted in some other way (e.g., by indentation, or by using italics instead of boldface). NS
- Section numbering: All sections, subsections, subsubsubsections must be numbered. Please use \\subsubsection instead of \\subsubsection*, etc. NS
Capitalization of Section headings: All section headings should be title case. (First letter of each word capitalized except for little words like "and" and "or".) This includes subsections, sub subsections, etc. NS, done
- Section headers: There must be some text separating all section headers. NS

## Tables and Figures

- Float placement: In general, floats should be at the top or bottom of the page (avoid using [h] option to \\begin{figure}). Check for pages that contain several floats and only 2-3 lines of text. These will be confusing for a reader, who is likely to miss the text. When this happens, please put the floats on a floats page ([p] specifier) instead. NA
- Floats should also be placed as close as possible to the page at which they are first referenced. You should not, e.g., place all of the figures at the end of the paper. NS, pretty good, def not at end.
Figures, tables should be centered. NS
- Captions should be underneath figures and tables. NS
- Captions NOT in italics, bold. NS `codeface` and \\url{}, but not egregious formatting.
- Tables and figures should not overfill margins. NA (manual check, reference urls run over, but correctly formatted)
- Multiline captions should have a hanging indent, that is, subsequent lines of the caption should be indented, aligning with the first word of the caption rather than the word "Figure". Usually this problem is caused by one of the other packages that you have included. Sometimes changing the order of includes will fix this (try moving the jmlr2e include farther down). NS

## Footnotes

- Footnote markers should follow punctuation. NA
- Footnotes should be complete sentences. NA

## Misc

- Dashes: When using dashes in text, please use --- instead of --, with no space before or after---like this. NS
- Data set: We use "data set" rather than "dataset". NS

## Citations
- Carefully read the section on citations in Instructions for Formatting JMLR Articles. A quick guideline is that the paper should still read correctly if all parenthesized text were omitted. Here are examples of BAD citations:
    - "See (Ginsberg, 1994) for an analysis..." [Uses citation as a noun]. NS, looks good
    - "Drummond (Drummond, 1994) showed that..." [Should be "Drummond (1994)"]. NS, looks good
    - "...the best method (see the ERT test (Davis, 1995))..." [double parens, should be "...best method (see the ERT test, Davis, 1995)..."] NA
- Citations not nested in parenthesis. Parentheses should not occur within parentheses, even for citations. Within parentheses use \citealt or \citealp instead. Or you can use \citep[e.g.,][]{smith00}.

## Object References

- use \\url commands to reference urls in papers. This causes hyperref to make the hyperlinks work nicely.
    - NS-- makes no difference in text, if fully qualified with https:// at the start.
- Parenthesis: \\eqref can sometimes result in parentheses within parentheses. When referencing an equation within a parenthetical statement, use Equation 1 rather than (1) or Equation (1). NA
- When referencing figures, sections, etc. ("Figure 1", "Section 2.1"), please make sure the words "Figure", "Section", etc., are uppercase. NS

## Math

- Punctuation: Math in formal writing should be punctuated as if the extra space is not there, for example, displayed equations should usually be followed by a comma or a period, depending on the surrounding text. NA
- Punctuation: Before displayed equations, punctuation (e.g., ":") is not necessary unless you would use the same punctuation if the equation were not there. NA
- In general, only equations that are referenced should be numbered. We are willing to relax this for equations that are particularly important, as others may wish to discuss these in later correspondence. NA
- Proofs should end with a filled box. NA
- Equations should not run over the right hand margin. Appendices are especially prone to this. NA
- Theorems, Lemmas, etc., should be labeled like Theorem 1, Theorem 2, Theorem 3, not as Theorem 2.1, Theorem 2.2, Theorem 2.3. NA

## References
- It is preferable to cite published papers, rather than tech reports. NS
- Author names: Make citations consistent. Either give the full first name of all cited authors, or give the first initials only for all cited authors. 
    - NS: I think rmd defaults to three names before et al. see thesis for .cls (.csl? from rjournal changing this)
- Capitalization in paper titles: Titles of conference papers should have the first word only titles. However, watch out for words like Bayes and Markov. These should still be capitalized, but BibTeX often leaves capitalized incorrectly.
    - NS: I think this is a bit unrealistic. They may push back about this one.
- Capitalization of book titles, etc: The parts in italics (book names, journal names, conf names) should be title case. (First letter of each word capitalized except for little words like "and" and "or".)
    - NS: I think this is a bit unrealistic. They may push back about this one.
- Please cite conference titles consistently. We do not have a enforced style for conference names, but whichever style you choose, be consistent. Don't refer to the same conference as "AAAI 2004" in one reference and the "The Nineteenth National Conference on Artificial Intelligence" in another one. Personally, I prefer the style "International Conference on Machine Learning (ICML)", leaving off the "Proceedings of the Twentieth..."
    - NS: I think this is a bit unrealistic. They may push back about this one.